### PR TITLE
Added requirements.txt for QGIS

### PR DESCRIPTION
**Pull request by tobwen**
Added the missing requirements.txt file to help QGIS installing the dependencies.

### CODE REVIEW

**Comment by XavierCLL** [comment]
Same here, you seem a bot...

**Comment by tobwen** [comment]
No, I'm not a bot. Sorry, a tool went wrong. I'll explain on the QGIS mailinglist.

**Comment by XavierCLL** [comment]
Send the link please, otherwise even your answer looks like a bot

**Comment by tobwen** [comment]
I've posted this message to the [dev-mailinglist](https://lists.osgeo.org/pipermail/qgis-developer/2024-October/thread.html) some minutes ago, might take some minutes until it will appear.

```
Dear plugin developers,

some of you may have received unexpected pull requests from me on GitHub today (user: tobwen). This was unintentional, and I have already closed all of these PRs. I'm not a bot, I'm a geographer ;)

Some context:
As missing dependencies in plugins are a recurring issue, I've been reviewing plugins to identify and update their requirements.txt files accordingly.

My goal was to set up an alternative plugin repository for internal testing, which would include the updated requirements.txt files. If successful, I intended to offer these updates to you via pull requests.

Unfortunately, I forgot to comment out the pull request part in my code. As a result, the files were not only pushed to my own plugin repository but also sent to you via GitHub. This never was to run without manual curation and of course not without a bugreport.

I sincerely apologize for this mistake. My intention was not malicious; I simply wanted to help address the dependency gaps.

Best regards,
Tobias
```

You can find me on X, OSM and we can meet on next FOSSGIS or Intergeo to proof I'm not a bot, but an idiot.

**Comment by XavierCLL** [comment]
That explains your PR on my plugins, thanks for taking the time to explain the situation to me.

**Pull request closed without merging**
